### ISSUE TITLE
rebar3 plugin

### ISSUE THREAD

**Issue by lpil** [lpil/gleam#10]

**Comment by hengestone** [comment]
Started looking at this, but the current project structure is not rebar3 friendly - I think promoting the current `compiler/` subdirectory to a top-level project might be required. See e.g. the `efene` language and plugins
https://github.com/efene/rebar3_efene_compile

**Comment by lpil** [comment]
The compiler would be published as a hex package which will be a regular dep of the rebar3 plugin, so no problem there.

You're right in that it would be a problem if using git to resolve the dependency, I've made an issue for this here https://github.com/erlang/rebar3/issues/1923

It may make sense to structure this repo as umbrella application containing multiple library applications, but I have not experimented with this yet. :)

**Comment by hengestone** [comment]
Yeah, it's a bit of a bootstrapping issue, this blog post does a pretty good job of describing submodules: https://blog.github.com/2016-02-01-working-with-submodules/ 

Ideally there should be a `gleam-compiler` repo under the current `compiler/` subdir

**Comment by lpil** [comment]
My intention is to keep all core projects in one git repo (i.e. a monorepo), so no need for submodules. I find it much easier to work with one large repository for tightly coupled projects.

**Comment by hengestone** [comment]
OK, I started that under my repo, but obviously rebar itself needs support for subdirs before it can be used as-is.

**Comment by lpil** [comment]
We could use rebar checkouts until packages are published

https://www.rebar3.org/docs/dependencies#section-checkout-dependencies

**Comment by hengestone** [comment]
Cool, I missed that in the rebar docs :+1:

**Comment by lpil** [comment]
Me too! tsloughter pointed it out to me

**Comment by hengestone** [comment]
Take a look at my gleam fork at https://github.com/hengestone/gleam under /gleam_rebar. That should have the code to do the actual compile step, adapted from Efene.

Feel free to build on that or discard as appropriate :)

**Comment by lpil** [comment]
Wonderful, thank you.
