### ISSUE TITLE
Pretty error for when a row is missing a field 

### ISSUE THREAD

**Issue by lpil** [lpil/gleam#118]

**Comment by Exadra37** [comment]
Sorry, but is just me or is unclear what to do in any issue labeled as **good first issue**... Am I missing something?

**Comment by lpil** [comment]
Hi Paulo! Seeing as there are no contributors I've not taken the time to fill in details. If you're interested in working on a specific issue I can guide you in the right direction. :)

**Comment by Exadra37** [comment]
Hi @lpil,

My comment was just in the sense of trying to understand the lack of context, because I don't know Rust and I am an Elixir beginner that misses static types ;)

Sorry to have mislead you in that I would be able to work on the issue.

**Comment by lpil** [comment]
That's no problem at all! Rust is not the most approachable language. Hopefully contribution will be easier soon :)

Thanks for your interest in Gleam!

**Comment by Exadra37** [comment]
I tried already for 3 times to learn Rust, but I always end-up to loose interest, despite that I love the principles of it.

I may add a docker image to Gleam if you have interest on it.

**Comment by lpil** [comment]
A docker image would be welcomed :)

**Comment by Exadra37** [comment]
I will add only a Dockerfile to this project and a bash script to wrap its use. I will open a PR for it when I have some time... see you there.
