### ISSUE TITLE
VS code syntax highlighting

### ISSUE THREAD

**Issue by lpil** [lpil/gleam#134]

**Comment by rawburt** [comment]
For reference https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide

**Comment by rawburt** [comment]
It's minimal at best, but here is the repo:

https://github.com/rawburt/vscode-gleam-syntax

It's a live extension in VS Code now.

The Web access to the extension will eventually be at https://marketplace.visualstudio.com/items?itemName=gleam-syntax.gleam-syntax

**Comment by tahscenery** [comment]
Hi, I know a bit about VSCode syntax highlighting and Regex (been working on my own highlighter for quite a while). I've been interested in the development of Gleam as well, and I'd be more than happy to help @rawburt with this! rawburt, if you require any assistance, please don't hesitate to let me know :)

**Comment by lpil** [comment]
Wonderful, thank you. I'll add this to the documentation.

**Comment by rawburt** [comment]
@ tahscenery Thanks! I'm quite a syntax highlighting n00b so feel free to provide any changes you feel are relevant to https://github.com/rawburt/vscode-gleam-syntax via Pull Request.
