### ISSUE TITLE
Additional list functions

### ISSUE THREAD

**Issue by lpil** [lpil/gleam#143]
- [x] all
- [x] any
- [x] at
- [x] concat
- [x] index_map
- [x] intersperse
- [x] sort
- [x] unique
- [x] zip

**Comment by rodr0m4** [comment]
Hi! This looks like a good first issue to tackle. I'd like to work on it :)

**Comment by lpil** [comment]
Wonderful! If you have any questions ask them here or in the irc channel. :)

Happy to accept multiple PRs or one big one, whatever works for you.

**Comment by rawburt** [comment]
Is the plan to have a `list` module to encapsulate these functions?

**Comment by lpil** [comment]
There is one already! See `gleam_stdlib/src/list.gleam`

**Comment by rawburt** [comment]
@lpil 

Is concat meant to return a flattened list? `[[1],[2]] -> [1,2]`
Or a string? `[1,2] -> "12"`

**Comment by rawburt** [comment]
@lpil  `Any takes a predicate function and returns true if all the elements in the list return True.` - Isn't this `all`?

**Comment by lpil** [comment]
Sorry, typo on my part. That is indeed all! Any is if at least one returns True for that predicate. contains doesn't take a predicate, instead it just checks for equality against each element.
