### ISSUE TITLE
Add a few examples

### ISSUE THREAD

**Issue by codec-abc** [lpil/gleam#145]
Hi,

Nice project!

In this current state, I would say that for someone not used to gleam it is hard to get a fell of what we can achieve with gleam. As such, adding a few examples of increasing complexity might be a good way to showcase your languages and show how to use gleam to design simple programs.

Also, if possible something like [play.rust-lang](https://play.rust-lang.org/) with working examples make it easier for people to try gleam without installing anything.

**Comment by lpil** [comment]
Yes, this is very much needed! Adding an examples section to the website is a priority.

**Comment by lpil** [comment]
Added an examples section here https://gleam.run/getting-started/example-projects.html

More will come later :)
