### ISSUE TITLE
Allow parenthesis around expressions

### ISSUE THREAD

**Issue by rawburt** [lpil/gleam#155]
<img width="274" alt="Screen Shot 2019-04-18 at 7 26 58 PM" src="https://user-images.githubusercontent.com/10911/56401893-f4a50e00-620f-11e9-85cd-2f8e2524fce9.png">

```
pub fn convert(temp) {
  case temp {
  | {"c", t} -> ((t*(9/5))+32)
  | {"f", t} -> ((t-32)*5/9)
  }
}
```

I've tried various forms of this and it seems arbitrary parenthesis are not allowed. Is this expected behavior?

**Comment by lpil** [comment]
Parenthesis would be nice but they would make the syntax ambiguous. Take this program:

```rust
fn run() {
  name
  (1 * 2)
}
```

Is it a discarded variable followed by a grouped expression or is it calling the function `name` with the argument `1 * 2`? Whitespace is syntactically irreverent in Gleam so we cannot tell.

If you wish to group expression to change precedence you can use `begin` `end`, which sadly is somewhat unwieldy.

**Comment by rawburt** [comment]
@lpil How would you approach writing `((t*(9/5))+32)`? If you do `t * 9 / 5 + 32` then `t*9` would happen first considering order of operations, no?

**Comment by lpil** [comment]
That expression evalutes to the same value if all the parens are removed, but if you want to change the precedence either use `begin end` or extract variables.

```rust
let x = 9 / 5
t * x + 32
```
```rust
t * begin 9 / 5 end + 32
```

**Comment by lpil** [comment]
I'm going to close this as there's no work to be done. If you have an idea for nicer syntax here please open a new issue. Thank you :)

**Comment by OvermindDL1** [comment]
> Is it a discarded variable followed by a grouped expression or is it calling the function name with the argument 1 * 2? Whitespace is syntactically irreverent in Gleam so we cannot tell.

Well in OCaml it would be the function `name` called with the single argument of `1 * 2`.  ^.^

**Comment by lpil** [comment]
OCaml is certainly more elegant here! :)

**Comment by edman** [comment]
I get an error with `begin .. end`. Is it no longer supported?

```
error: Unknown variable
   ┌─ 
   │
29 │     7 * begin 9 / 5 end + 32
   │         ^^^^^ did you mean `Seattle`?

The name `begin` is not in scope here.
```

**Comment by lpil** [comment]
Hello! It use braces these days

```rust
7 * { 2 + 3 }
```
