### ISSUE TITLE
Labelled function arguments

### ISSUE THREAD

**Issue by dym-sh** [lpil/gleam#158]
imo, optionally named function arguments (like in [OCaml](https://caml.inria.fr/pub/docs/u3-ocaml/ocaml051.html#htoc52)) would be meaningful

**Comment by lpil** [comment]
I agree, that would be a nice feature! I could see named arguments for both functions and enums being very useful. Let's add this to the TODO list.

**Comment by lpil** [comment]
Some discussion in the Rust community https://internals.rust-lang.org/t/pre-rfc-named-arguments/3831/196

**Comment by lpil** [comment]
Some information on Swift's approach:
https://docs.swift.org/swift-book/LanguageGuide/Functions.html

**Comment by tmbb** [comment]
> We may want a shorthand if the variable name and the label are the same.

I think that's overcomplicating the syntax for a very little gain.

**Comment by lpil** [comment]
Hi @tmbb ! So you would prefer not to have the shorthand syntax for when the variable name and label are the same?  
If you have some code snippets to share that would be appreciated, thank you :)

**Comment by tmbb** [comment]
> So you would prefer not to have the shorthand syntax for when the variable name and label are the same?

Well, maybe having the abbreviation would save a lot of typing, IDK. But the point I want to carry across is that Gleam already seems syntactically very complex, and adding more complexity on top of it doesn't seem like the correct thing to do IMO. But I'm very partial towards simple syntax, others are free to disagree 😄

**Comment by lpil** [comment]
> Gleam already seems syntactically very complex

This is good feedback, thank you! I've been working to make the grammar as small as possible so I would definitely be interested in examples of the complexity.

Currently I believe we're very small (on similar levels to Erlang!) and much much simpler than Elixir but I'm sure there's improvements we can make before we stabilise the syntax.

**Comment by tmbb** [comment]
> so I would definitely be interested in examples of the complexity.

It's not thaaat complex, to be fair. It's just that having very complex things inside function heads seems inelegant to me. But that is just my opinion...

**Comment by lpil** [comment]
Could you give an example of the very complex things? Thanks

**Comment by tmbb** [comment]
> Could you give an example of the very complex things? Thanks

**Comment by tmbb** [comment]
> Could you give an example of the very complex things? Thanks

To me, this is simple:

```
pub fn sub(string, from as position, remove as length: Int) {
  // ...
}
```

but being able to have something like:

```
pub fn sub(string, #from, remove as length: Int) {
  // ...
}
```

(where `#from` is equivalent to `from as from`), which saves just a couple of characters, seems more complex than it should. All of this is subjective, though...

**Comment by lpil** [comment]
That's great, thank you :)

**Comment by OvermindDL1** [comment]
I personally find the `xxx as yyy` exceptionally hard to read for some reason.  I don't know which side is the public and which is internal, I don't know why the right has the typing indicator but the left doesn't (why not `remove: Int as length` for example).  And I'm not sure why you would want different public and internal names, doesn't that mean that one side or the other is misnamed?

**Comment by lpil** [comment]
After writing some Gleam today using this new syntax I am inclined to agree, it is very easy to get wrong. I shall try some more things :)
