### ISSUE TITLE
Arch Linux AUR package

### ISSUE THREAD

**Issue by NobbZ** [lpil/gleam#159]
As I want to prepare an Arch Linux `PKGBUILD` with the aim to publish it on the [AUR](https://aur.archlinux.org/), I need to know what has to be installed on the system and where it is expected to be.

The makefile currently just compiles the compiler and copies it to `~/.cargo/bin/gleam`, is this enough? Or does some stdlib has to be installed additionally? I do see, that there are extra tags for `stdlib` versions.

**Comment by lpil** [comment]
Just publishing the `gleam` binary is sufficient, the stdlib is distributed via hex package and will normally be downloaded by rebar3.

**Comment by NobbZ** [comment]
Thanks for the info!

Then its done, the [`gleam` package on the AUR](https://aur.archlinux.org/packages/gleam/) will install the single `gleam` executable to `/usr/local/bin`.

**Comment by lpil** [comment]
Thank you :)

It looks like the URL is wrong, it should be https://gleam.run

**Comment by lpil** [comment]
Should I add this to the installation guide?

**Comment by NobbZ** [comment]
I already fixed the URL, in the upstream repository at least, need to check in a couple of minutes if CI passed ;)

And yes, I think mentioning in the installation guide that it is available in the AUR is a good thing. I have no clue though how easy it is to create packages for other Linux distributions.

**Comment by lpil** [comment]
Thank you. I'll re-open this to remind me.

**Comment by lpil** [comment]
I'm unfamiliar with AUR. Is there a command that Arch users can run to install the package?

**Comment by seubert** [comment]
I'm pretty new to the Arch ecosystem but I think most people use a separate tool, such as `yaourt` or `yay`. If doing it by hand you have to use `makepkg` on the tarball from AUR. @NobbZ correct me if I'm wrong, please!

**Comment by NobbZ** [comment]
Basically, those who use Arch Linux will probably know how to deal with packages from the [AUR](https://wiki.archlinux.org/index.php/Arch_User_Repository).

Many use one of the plenty [AUR helpers](https://wiki.archlinux.org/index.php/AUR_helpers), tools which manage downloading, building and installing the package and also informing the user about updates.

Some of them blend pretty well–or even replace–the regular package manager.

The vanilla way though is to `git clone` from the packages URL, for `gleam` it is https://aur.archlinux.org/packages/gleam/. then `cd`ing into the cloned folder and using `makepkg` to build the actual package and `pacman -U` to install the package into the system. One has to check for updates and even build/install dependencies only distributed from the AUR by hand.

Especially the latter is the main reason why most people use the afore mentioned helpers or no AUR at all.

I'd suggest something like the following paragraph:

```md
### Arch Linux

`gleam` is available through the [Arch User Repository](https://wiki.archlinux.org/index.php/Arch_User_Repository)
as package `gleam`. You can use your prefered [helper](https://wiki.archlinux.org/index.php/AUR_helpers)
to install it or clone it for manual build from [https://aur.archlinux.org/gleam.git](https://aur.archlinux.org/gleam.git).
```

**Comment by lpil** [comment]
Thank you
