### ISSUE TITLE
map_dict:fold

### ISSUE THREAD

**Issue by lpil** [lpil/gleam#173]
```rust
map_dict:fold(MapDict(k, v), acc, fn({k, v}, acc) -> acc) -> acc
```

Or

```rust
map_dict:fold(MapDict(k, v), acc, fn(k, v, acc) -> acc) -> acc
```

The latter doesn't allocate a tuple but the former has a sig closer to `list:fold` which may be useful if we were to introduce some form of type classes like structure

**Comment by bsnyder788** [comment]
@lpil I can tackle this one. What version do you prefer?

**Comment by lpil** [comment]
I'm not sure. Do you have any preferences?

**Comment by bsnyder788** [comment]
I prefer the latter, but I'm not sure what the advantages of the type class structure you are referring to might be for the first one you proposed. Care to elaborate on what you actually mean for the tupled version?

**Comment by lpil** [comment]
I'm not sure really. Let's go for latter :)

**Comment by bsnyder788** [comment]
https://github.com/lpil/gleam/pull/179
