### ISSUE TITLE
Module pattern

### ISSUE THREAD

**Issue by lpil** [lpil/gleam#190]
Useful for using unqualified functions from another module in a limited scope

```rust
import gleam/result

pub fn run(x) {
  let module { then map } = result
  x
  |> then(one)
  |> then(two)
  |> map(three)
}
```

**Comment by OvermindDL1** [comment]
Just for comparison, that's the `open` keyword in OCaml:

```ocaml
(* unopened *)
let _ = SomeModule.blah 42

(* global open (this is not exported to the interface, I.E. `blah` does not get exported *)
open SomeModule

let _ = blah 42

(* Local open *)
let _ =
  let open SomeModule in
  blah 42

(* Scoped open *)
let _ =
  SomeModule.(
    blah 42
  )
```

In addition OCaml has a way to open another module and re-export everything it included via `include`:
```ocaml
include SomeModule
```
This is essentially like copy/pasting `SomeModule` into this file, the same bindings and types will match and be identical and all.  You can then proceed to redefine things as well if you wish.  This is a super common pattern for extending things like a List or some library specific type with new functionality.
