### ISSUE TITLE
Generate init templates with Gleam CLI

### ISSUE THREAD

**Issue by AdamBrodzinski** [lpil/gleam#192]
It would be nice to remove the [rebar_gleam](https://github.com/gleam-lang/rebar_gleam) plugin dependency so that early adopters can have a better onboarding experience. Not only is it an extra step to setup, it can get outdated and updating it is not obvious to non Erlang users.

This proposal would add a CLI command like `gleam new my_amazing_application`. This would generate the same files that the rebar plugin would. Alternatively `gleam init ...` could work as well.

**Comment by lpil** [comment]
`gleam new` sounds good.

To add a new subcommand to the compiler you'll need to create a new Command enum variant and pattern match on it in main

https://github.com/lpil/gleam/blob/2b7a0916573ac042989678d9cdde740ae9d59a4b/gleam/src/main.rs#L48-L65

**Comment by AdamBrodzinski** [comment]
Awesome, thanks for pointing me in the right direction, very much appreciated! 👍

**Comment by lpil** [comment]
Hi @AdamBrodzinski, did you make any progress with this one? :)

**Comment by AdamBrodzinski** [comment]
Hey there! I tinkered a little getting up to speed on Rust going through The Rust Book (first time using it) but haven't actually had time to attempt the PR. The week of the 29th I have off work so I was planning to try it out then.

However, if this is something you're wanting sooner, i'm more than happy to have someone else PR as I don't want to hold you back

**Comment by lpil** [comment]
Cool, sounds good! Rust is a pain to get started with so please do open WIP PRs if you get stuck with anything or have any questions, I'm very happy to help out with whatever :)

**Comment by AdamBrodzinski** [comment]
Awesome, will do! This will be a great feature to get my feet wet. It's one of those things that would take an hour in Elixir but will take some time to learn the Rust ways 😄

**Comment by lpil** [comment]
I'm gunna pick this up, thanks :)

**Comment by AdamBrodzinski** [comment]
Awesome, thanks @lpil 💪
