### ISSUE TITLE
Set up patreon and/or opencollective 

### ISSUE THREAD

**Issue by ontofractal** [lpil/gleam#194]
I would be happy to pitch in to support Gleam development and your other projects. Thanks!

**Comment by lpil** [comment]
Thanks for your support! Off the back of this I've signed up for the GitHub sponsors program. If I'm accepted I'll link it to this project. Thanks! :)

**Comment by lpil** [comment]
I've not heard anything on this front. If anyone knows how to get bumped up the queue please let me know :)

**Comment by lpil** [comment]
I've been accepted, hooray! :) I've also added a sponsors link to this project.
