### ISSUE TITLE
Remove first class modules

### ISSUE THREAD

**Issue by lpil** [lpil/gleam#196]
After using them for a while in Gleam code I don't think that first class modules are the best choice without OCaml style modules functors. There's no way to compose or construct them so in practice they become quite limited.

Remove them, reclaim the `:` operator, and add polymorphism to the `.` operator to work with both maps and modules.

**Comment by OvermindDL1** [comment]
Without Functors First Class Modules are little more than type-based witnesses, which could still have uses, but you really should add a Functor system, it's not that hard to implement (especially since modules are essentially just type-based records ^.^).

**Comment by lpil** [comment]
You've hit the nail on the head there, they're really not all that without Functors.  I'm going to remove them for now and defer the decision about adding Functors as they could be added easily later.
