### ISSUE TITLE
Keeping module imports fully qualified?

### ISSUE THREAD

**Issue by Qqwy** [lpil/gleam#227]
In the documentation section on [module imports](https://gleam.run/tour/module.html#import), `nasa/rocket_ship` is imported, which then allows one to call `rocket_ship:launch()`.

However, this means that the `nasa` part of the module disappears. In a more complicated project, I'd imagine modules to be nested multiple directories deep, with similar lowest-level module names being used (e.g. `game/user`, `billing/user`, `statistics/user`). 

The second example given alludes somewhat to this situation: Here we have `unix/cat` and `animal/cat` where the second is aliased to `kitty`. Is there a way to keep both fully qualified? I think that there are many situations in which writing out `unix/cat` and `animal/cat` is more clear than renaming them.

**Comment by lpil** [comment]
In the situation described I would suggest giving the module a descriptive name `import unix/cat as unix_cat`. This is a bit repetitive though, so perhaps a shorter way of doing this could be good.

The suggested syntax isn't possible as it clashes with integer division- what could we do instead?

**Comment by Qqwy** [comment]
What about using the `:` delimiter for that as well, since it is already used to delimit modules from function names?
So the given examples would be: `nasa:rocket_ship:launch()` or `unix:cat:purr()`?

And then I think it might make sense to have a keyword like e.g. `require` which allows you to reference the other module without aliasing the module name, and keeping `import` as is.

Does that make sense?

**Comment by lpil** [comment]
Modules are not module namespaces, so that would require overloading the `:` operator to work on both namespaces and modules. I am however reworking modules so perhaps this could be possible later.

I wish to avoid having more than one `import` type statement, this is a frequent cause of confusion for Elixir newcomers.

**Comment by Qqwy** [comment]
Can you enlighten me on the difference between modules and module namespaces? Is it in the current Gleam possible to define functions inside `nasa` (which in the `nasa/rocket_launch.gleam` example is foremost a namespace) itself as well?

In the case where you want to avoid adding multiple keywords, I personally think that by default not aliasing things would make more sense (i.e. following the principle of least astonishment) with having an alternate syntax like `import x as y` that does name aliasing.
Although in that case I think that a name other than `import` probably makes more sense :thinking: ...

I am not sure about your own experiences in this field, but for me personally (in the code that I write and in the code that I have seen) I think that it is much more common to call something (that is part of either the standard library, some third-party library or another module in my own code) using its fully qualified name than aliasing it. Aliases are only used when a name is very long and calling into that other module is very common.

**Comment by lpil** [comment]
For `one/two` the module `two` resides in the namespace `one/`. It is not a member of a module named `one` and so you cannot do this:

```rust
import one

fn run() {
  one:two:run()
}
```

> In the case where you want to avoid adding multiple keywords, I personally think that by default not aliasing things would make more sense (i.e. following the principle of least astonishment)

Let's not talk about the principal of least astonishment as this is not an objective measurement, it depends on the person and their experiences. Gleam's import naming system will likely feel less familiar to Elixir and Haskell users, but more familiar to Python, Java and NodeJS users. Rust users may be somewhere in the middle.

Let's suggest possible syntax and semantics in this issue and if something looks good we can add it later, even if it means a breaking change. This will be a low priority though as the same can be achieved today using `import one/two as one_two`

**Comment by lpil** [comment]
Going to close this now as we don't have anything to work on and I'm cleaning up the issues list. Please feel free to reopen in the suggestions repo, thank you! :)
