### ISSUE TITLE
Can not use `struct` in `enum` variant

### ISSUE THREAD

**Issue by NobbZ** [lpil/gleam#229]
The following will result in an error:

```gleam
pub enum T(a, b) =
| T(struct(List(a), b))
```

```plain
error: Syntax error
- </home/nmelzer/projects/tlob/src/tlob/combi.gleam>:2:5
  |
2 | | F(fn (List(sym)) -> List(struct(List(sym), tree)))
  |     ^^ Unexpected token
  |
```

**Comment by lpil** [comment]
`struct` is a new feature that only exists on the master branch. If you're using v0.3 please using the tuple syntax `T({List(a), b})`. Sorry for the confusion!

**Comment by NobbZ** [comment]
Then please remove the `struct` section from the book and replace it with a chapter about tuples.

Or put a big warning that it won't work with v0.3.0 in the book…

**Comment by lpil** [comment]
This has already been done :)
