### ISSUE TITLE
Replace anonymous struct type with stdlib Pair and Triple

### ISSUE THREAD

**Issue by lpil** [lpil/gleam#234]
With named structs the tuple/anonymous struct type does not have clear value as a special case in the compiler. A change inspired by Purescript and Kotlin.

```rust
pub struct Pair(a, b) {
  first: a
  second: b
}

pub struct Triple(a, b, c) {
  first: a
  second: b
  third: c
}
```

We could perhaps rename the tuple module to Pair and make a new module for Triple.

**Comment by scripttease** [comment]
Hi, I'm a bit of a noob, and I won't be able to remove anonymous struct type I don't think but I'd like to have a go at adding Pair and Triple if that's ok?

**Comment by lpil** [comment]
Sure thing! Let me know if there is anything I can help with :)

**Comment by lpil** [comment]
@scripttease I've removed the anonymous struct from the compiler in this PR and left notes of some places that need to be updated to use a new `Pair` type. Hopefully this will be some help for your addition of `Pair` and `Triple` https://github.com/lpil/gleam/pull/237

**Comment by scripttease** [comment]
PR for pair here: https://github.com/lpil/gleam/pull/242
