### ISSUE TITLE
Pair map functions

### ISSUE THREAD

**Issue by lpil** [lpil/gleam#245]
```rust
fn map_first(Pair(a, b), fn(a) -> c) -> Pair(c, b)
```
```rust
fn map_second(Pair(a, b), fn(b) -> c) -> Pair(a, c)
```

**Comment by OvermindDL1** [comment]
Instead of making lots of special case functions like this, it would probably be better to add in built-in Lens support to the language, then functions like these as well as any others for any size tuples, records, etc... would then come 'for free'.

**Comment by lpil** [comment]
For sure, more powerful constructs will come later :)

**Comment by bsnyder788** [comment]
https://github.com/lpil/gleam/pull/267
