### ISSUE TITLE
Pattern matching the values of two different variables

### ISSUE THREAD

**Issue by gwaerondor** [lpil/gleam#254]
It isn't possible to pattern match one variable to another in a case statement.
```
pub fn match_cases() -> String {
  let x = 1
  let y = 2
  case x {
  | y -> "Same!"
  | _ -> "Different."
  }
}

pub fn match_cases_test() {
  match_cases() |> expect.equal(_, "Different.")
}
```
The test fails and the compiler reports that the variables Y and Y1 are unused.
(Similar issue to #253 but with two different variable names)

**Comment by lpil** [comment]
Variable in Gleam can be reassigned, so this will not be supported. We will however have something like this:

```rust
case x {
| [y] when y == z -> 1
| other -> 0
}
```

I'll close this issue and track this in the other one. Thanks!
