### ISSUE TITLE
Unqualified imports

### ISSUE THREAD

**Issue by lpil** [lpil/gleam#259]
Enable the importing of module fields so that they can be used in an unqualified fashion.

Possible syntax:

```rust
import gleam/pair.{Pair}

fn main() -> Pair(Int, Int) {
  Pair(1, 2)
}
```

**Comment by djKooks** [comment]
@lpil hello~just hope you could help me...
I've make some changes, and currently:
```
import gleam/pair -> pr
```
this grammer passes, but

```
import gleam/pair -> Pair
```
returns:
```
3 | import gleam/pair -> Pair
  |                      ^^^^ Unexpected token
  |

Expected one of r#"[a-z][0-9a-z_]*"#
```
Where can I fix this?

**Comment by lpil** [comment]
Hi @djKooks ! I think the syntax we're after is more like this:


```rust
import gleam/pair.{Pair, map_first}
```

The syntax with `->` has already been implemented for functions so no need to worry about that :)

**Comment by djKooks** [comment]
@lpil hello~have some question.
I'm checking `grammer.lalrpop` file, and it seems this is allowing `as` for renaming function name, such as:
```
import gleam/pair as gpair
```
In this case how do we should define when importing multiple module field, like:
```
import gleam/pair.{Pair, first} as ???
```

Thanks.

**Comment by lpil** [comment]
I've not settled on what the exact syntax should be yet but this is my current thinking:

```python
import gleam/pair.{ Pair as PairConstructor, first as first_function } as list_module
```

**Comment by djKooks** [comment]
@lpil hmm...then in this case, are these same?
- list_module.Pair(X, Y)
- PairConstructor(X, Y)

**Comment by lpil** [comment]
Yes, that's right.

**Comment by djKooks** [comment]
@lpil oh, is it updated?

**Comment by lpil** [comment]
Yes, I finished this off yesterday, minus the aliasing using `as`
