### ISSUE TITLE
Terminal inline issue

### ISSUE THREAD

**Issue by djKooks** [lpil/gleam#272]
Hello,
While working on gleam, I've found some issue like this...
```
$ gleam build
Compiling gleam/result
Compiling gleam/iodata
Compiling gleam/pair
...
$ rebar3 shell
===> Verifying dependencies...
===> Compiling hello_world
...
```
After this, when I run `gleam build` again, terminal shows like:
![Screen Shot 2019-10-08 at 20 13 36](https://user-images.githubusercontent.com/1720209/66391466-28673080-ea08-11e9-83c8-fdbfd38383a1.png)

Seems there are problem in tab/space setting...is this known problem?
I'm using:
- MacOS,
- iTerm2 + zsh

Thanks.

**Comment by djKooks** [comment]
Oh, sorry.
Maybe could ignore this one. It also causes on `rebar3 shell` command. Seems like issue of terminal.

**Comment by djKooks** [comment]
Sorry...this one:
https://github.com/erlang/rebar3/issues/536

**Comment by lpil** [comment]
Nice detective work :)
