### ISSUE TITLE
Incorrect precedence for infix `+`, `-`, `+.`, `-.`

### ISSUE THREAD

**Issue by adituv** [lpil/gleam#3]
https://github.com/lpil/gleam/blob/17ed8014292e4b95f1fcaa503328dad6e72fef59/src/gleam_parser.yrl#L17

These should all be left-associative with precedence between that of comparisons and `*`, `/`.  Elixir has them at precedence 210 ([elixir_parser.yrl](https://github.com/elixir-lang/elixir/blob/0ae082de54c80d267b6ba4fb3b6ad311360fdcde/lib/elixir/src/elixir_parser.yrl#L72-L74)).

**Comment by lpil** [comment]
Thanks! I mixed up unary + and binary +, oops
