### ISSUE TITLE
Example project using rebar3 hooks to run compiler

### ISSUE THREAD

**Issue by lpil** [lpil/gleam#58]
https://github.com/purerl/purerl_otp_sandbox

**Comment by tsloughter** [comment]
Shouldn't need to use hooks now that rebar3 has a new concept of project builders. This is how `mix` is supported and should work similarly.

**Comment by lpil** [comment]
That may be the long term solution but it's considerably easier for me to add this to `rebar.config` than to learn and implement a project builder

```
{pre_hooks, [{"(linux|darwin|solaris|win32)", compile, "gleam build ."}]}.
```
