### ISSUE TITLE
Escape function names if they collide with Erlang keywords

### ISSUE THREAD

**Issue by lpil** [lpil/gleam#65]
## Keywords
- if
- case
- !
- receive
- bnot	
- div	
- rem
- band	
- bor	
- bxor	
- bsl	
- bsr	
- not
- and
- or
- xor	
- orelse
- andalso
- when
- end
- fun
- try
- catch
- after

**Comment by michallepicki** [comment]
Or maybe instead of escaping the function names, do not allow these names at all?

**Comment by lpil** [comment]
I don't want to tie the language to the the syntax of the compile target too much, at least not yet. I could imagine a future were we compile to Javascript, WASM, Go, etc- would we also add the keywords of those languages to Gleam's reserved words?
