### ISSUE TITLE
Function captures

### ISSUE THREAD

**Issue by lpil** [lpil/gleam#78]
```rust
foo(_, 1)
```

Is equivalent to 
```rust
fn(x) { foo(x, 1) }
```

**Comment by OvermindDL1** [comment]
I supported that format in my MLElixir project as well for explicit partial application as well, however I also supported `_1`, `_2`, `_3`, etc... for repositioning arguments as well, like via `foo(_3, a, _1, _2, b)` became `fun a1 a2 a3 -> foo(a3, a, a1, a2, b)`.  I found it very useful.  :-)

**Comment by lpil** [comment]
That's a nice suggestion, thanks!
