### ISSUE TITLE
Pipe operator

### ISSUE THREAD

**Issue by lpil** [lpil/gleam#79]
```rust
1 |> run
```

Parsing and typing is done, but the code generator is currently incorrect.

**Comment by OvermindDL1** [comment]
Question, do you really need to hardcode the pipe operator?  Can't it just be a normal defineable operator?  Thus in OCaml parlance:
```ocaml
let (|>) v f = f v
```
Can be defined as the pipe operator in the prelude, or can be redefined by the users?

**Comment by lpil** [comment]
There's no reason why it needs to be hard coded from a type point of view but Gleam does not currently permit the defining of custom operators.

**Comment by OvermindDL1** [comment]
> There's no reason why it needs to be hard coded from a type point of view but Gleam does not currently permit the defining of custom operators.

Well that sounds like a much needed feature!  ^.^

Don't forget to allow their precedence to be set!  OCaml has a...weird way of setting that, don't follow it's model, make it actually part of the declaration directly somehow like some other languages.  :-)

**Comment by lpil** [comment]
I'm not a fan of custom operators, I think they make the language harder to pick up in exchange for a small amount of tenseness.

**Comment by OvermindDL1** [comment]
Eh custom operators are very useful, such as `|>` for piping, `<|` for application, various monad and other category operators are all very standard, async work, etc...

The OCaml community is a good model here, operator defining is *extremely* looked down upon except in a few very well set cases such as the async libraries, category work, parsers, etc...
