### ISSUE TITLE
Development/Contributor Documentation

### ISSUE THREAD

**Issue by MainShayne233** [lpil/gleam#81]
This project looks really exciting, and I would love to make an attempt at contributing! It'd be wonderful if there was some documentation about how to build/start working on the project.

**Comment by lpil** [comment]
Thank you for your support! We're not quite ready for this but I'll make some documentation as soon as possible. Thank you!

**Comment by MainShayne233** [comment]
Wonderful! Looking forward to it. :)

**Comment by lpil** [comment]
I'm going to keep this open as a to-do for myself.

**Comment by lpil** [comment]
I've added a contributing document and have tagged some suitable issues

https://github.com/lpil/gleam/blob/master/CONTRIBUTING.md

https://github.com/lpil/gleam/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

Please open a new issue if you can think of ways to improve this! Thank you

**Comment by MainShayne233** [comment]
Awesome! Thanks for following up on this :)

**Comment by lpil** [comment]
No problem!
