### ISSUE TITLE
Allow numbers in function names

### ISSUE THREAD

**Issue by lpil** [lpil/gleam#93]

**Comment by cmkarlsson** [comment]
I had a look at this, but then I don't really know the details. I guess it requires some specification. What identifiers are allowed in what places?

Currently function names can be `VarName` which is `[a-z][A-Za-z_]*`. Just changing this to alpha-numeric works `[a-z][\w_]*` but is that too broad of a change?

**Comment by lpil** [comment]
It is not what I was thinking but could be even better. Unicode support is good for people speak languages other than English.

Can we think of any characters it matches that we might not want?

**Comment by lpil** [comment]
Oh! Sorry! I wish to disallow uppercase letters in variable names.
